# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='device_status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='server_info',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.RemoveField(
            model_name='handlelog',
            name='asset_info',
        ),
        migrations.RemoveField(
            model_name='handlelog',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='server_info',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='server_info',
        ),
        migrations.RemoveField(
            model_name='osinstall',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='osinstall',
            name='server',
        ),
        migrations.AlterIndexTogether(
            name='server',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='AdminInfo',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='HandleLog',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='NetworkDevice',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='OsInstall',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
